### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by Palmstroemen** [pierredarrieutort/fitext#11]
File 'fitext.min.js' not found. There is also no .min. file provided. In 'dist' -folder I just can find .cjs. .esm. and .umd. files. No one of them works. :-(

**Comment by pierredarrieutort** [comment]
Hello @Palmstroemen,

I've fixed this mistake in the README, you can now use the `fitext.js` file in the `src` folder to use it as a "no-module" component.

Thanks for your feedback 🙂

**Comment by Palmstroemen** [comment]
Salut Pierre! Merci pour respondier assez vite.
Voilà c'est que je fais:

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <div class="fit-this-text">
       <div class='fitter'>
        <h1>Resize your window</h1>
        <h2>Play with responsive 💡</h2>
        <p>A Vor den U-Ausschuss trat am Mittwoch als Erster die "blaue Glücksfee" Peter Sidlo (FPÖ) und hat dabei zunächst seine Eignung für den Posten im Vorstand der Casinos verteidigt. Er wurde im März 2019 zum Vorstand für Finanzen der Casinos Austria AG (Casag) bestellt, auf Vorschlag des damaligen Miteigentümers Novomatic. Zu dem Gutachten, das ihn als nicht für den Job qualifiziert darstellt, sagte Sidlo vor dem Ausschuss, dass er es aus dem Akt kenne – damals habe er es nicht gekannt. Seine spätere Absetzung – wegen Vertrauensverlusts – sei ungerechtfertigt gewesen, "und das habe ich auch eingeklagt". Ihm sei kein Fehlverhalten bewusst. Die Causa liegt beim Handelsgericht Wien, aber die Abteilung hat gerade keinen Richter.

Zu seiner FPÖ-Nähe sagte er: "Ja, es stimmt, ich war für eine österreichische Partei in der Vergangenheit ehrenamtlich tätig." Fügte jedoch hinzu: "Ich war aber nie Berufspolitiker, sondern habe mein ganzes Berufsleben in der Finanzwelt verbracht." Heinz-Christian Strache, ehemaliger FPÖ-Vizekanzler, habe Sidlos Bewerbung unterstützt – aufgrund seiner Qualifikation, nicht aufgrund des Parteibuchs.
</p>
       </div>
    </div>
</body>
<script src='dist/fitext.min.js' defer></script>
<script>
    const EVENTS = ['DOMContentLoaded', 'resize']
    EVENTS.forEach( e => window.addEventListener( e, () => fitext(true, .25) ) )
</script>
</html>

La ligne bleue, j’avais aussi essayé:
<script src='dist/fitext.cjs.js' defer></script>
<script src='dist/fitext.esm.js' defer></script>
<script src='dist/fitext.umd.js' defer></script>


Mon français n’est pas très bon. Alors, je suis heureux aussi about an answer in English. ;-)

Best regards,
Oliver

**Comment by Palmstroemen** [comment]
Hi again!

I’ve added this <div class=‚fitter‘> because I found it in the live-example.

Finally as no .min. file is provided, maybe the example needs some actualization? Copy-Paste does not work at all.

Best regards,
Oliver

**Comment by Palmstroemen** [comment]
Hi again,

Sorry. Just tried also the line: <script src='./src/fitext.js' defer></script> and left away the <div class=‚fitter‘> but still doesn’t work.

Best regards,
Oliver

**Comment by pierredarrieutort** [comment]
Hey !

You say right !

I will rework all the demo code because it's a very deprecated snippet 😅 !
And I will implement a minified file in the dist directory.


I will tell you when it will be okay. At this time I don't have enough time to do these features, I will start to see it this night but if you want you can do a pull request with the demo reworked 😛

**Comment by Palmstroemen** [comment]
Ok. Great! Thanks. No hurry!

**Comment by pierredarrieutort** [comment]
I've updated all the demo, you can go [here ](https://pierredarrieutort.github.io/fitext/)and use the umd module as is the demo to use fitext 😃 !

All is ok to you ?

**Comment by Palmstroemen** [comment]
Hm. The example-code still does not work here. BUT the demo works perfectly in my browser (chrome). When I copy the code and paste it into my BRACKETS-editor and then run it from there (in chrome), also the demo does not work. It does not change the size of the letters.

**Comment by pierredarrieutort** [comment]
Anything is written in your console ? If you don't give me more details I can't help you 😅

**Comment by Palmstroemen** [comment]
Hi again!

This is written in my console:
```
style.css:1 Failed to load resource: net::ERR_FILE_NOT_FOUND

VM30117:1047 WebSocket connection to 'ws://localhost:8125/' failed: 
Error in connection establishment: net::ERR_CONNECTION_REFUSED
createWebSocket @ VM30117:1047

favicon.png:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
```

**Comment by pierredarrieutort** [comment]
Ok, the console say nothing about fitext 🤔... Hmmm

Can you make a minimum reproducible repository ?

**Comment by Palmstroemen** [comment]
Hm ... So that's what I've done:

Take a late 2008 MacbookPro running MacOS 10.14.6 Mojave.
Run the recent version of Chrome
Navigate to: https://pierredarrieutort.github.io/fitext/
Try out everything and enjoy how it should be working.
Right-click and select: "show source code"
Copy everything [cmd + A] [cmd+C]
Open a new file in Brackets
Paste everything [cmd + V]
Save it as "fitest.html"
Click the live-preview-button in Brackets which opens a new Chrome-Window.
See that the size of the letters do not adopt to the screen-size.  :-(
Try the exactly same thing on an 2015 Lenovo Win10 with the exact same result.
Be sad.
Open an issue.

So it's EXACTLY the same code in exactly the same browser that works one time and doesn't the other.

**Comment by pierredarrieutort** [comment]
Sorry but when I read this, the origin of all this issue seems to be from your plugins or something in your computer 😕

**Comment by Palmstroemen** [comment]
yeah. It seems to be wired. Thanks for your support and at least the example in the read.me is up do date now. :-)
